bionic_university_market:
    resource: "@BionicUniversityMarketBundle/Controller/"
    type:     annotation
    prefix:   /

bionic_university_blog:
    resource: "@BionicUniversityBlogBundle/Controller/"
    type:     annotation
    prefix:   /

