parameters:
services:

    abstract_notification:
        class: BionicUniversity\Bundle\BlogBudle\Notification\AbstractNotification
        calls:
            - [setSecurityContext, [@security.context]]
        abstract: true

    email_notification:
        class: BionicUniversity\Bundle\BlogBudle\Notification\EmailNotification
        calls:
            - [setMailer, [@mailer]]

    html_email_notification:
        class: BionicUniversity\Bundle\BlogBudle\Notification\HtmlEmailNotification
        calls:
            - [setTemplating, [@templating]]

    image_resizer:
        class: BionicUniversity\Bundle\BlogBundle\Resizer\ImageResizer
        arguments: [%thumb_size_height%, %thumb_size_width%]
        calls:
            - [setImageService, [@imagine, @filesystem] ]

    post_subscriber:
        class: BionicUniversity\Bundle\BlogBundle\EventSubscriber\PostSubscriber
        arguments: [@security.context]
        tags:
            - {name: kernel.event_subscriber, event: post.create, method: onPostCreate}

    post_listener:
        class: BionicUniversity\Bundle\BlogBundle\EventListener\PostListener
        tags:
            - {name: doctrine.event_listener, event: prePersist, connection: default}

    imagine:
        class: Imagine\Imagick\Imagine
        public: false
