parameters:
services:
    image_resizer:
        class: BionicUniversity\Bundle\BlogBundle\Resizer\ImageResizer
        arguments: [%thumb_size_height%, %thumb_size_width%]
        calls:
            - [setImageService, [@imagine, @filesystem] ]

    post_subscriber:
        class: BionicUniversity\Bundle\BlogBundle\EventSubscriber\PostSubscriber
        arguments: [@security.context]
        tags:
            - {name: kernel.event_subscriber}

    imagine:
        public: false
        class: Imagine\Imagick\Imagine