parameters:
services:
    image_resizer:
        class: BionicUniversity\Bundle\BlogBundle\Resizer\ImageResizer
        arguments: [%thumb_size_height%, %thumb_size_width%]
        calls:
            - [setImageService, [@imagine, @filesystem] ]

    imagine:
        public: false
        class: Imagine\Imagick\Imagine